image: python:3.6

test:
    script:
        - pip install --upgrade pip
        - pip install numpy
        - pip install scipy
        - pip install nose
        - pip install coverage
        - pip install codecov
        - nosetests --with-coverage
        - codecov --token=83ec5fee-5f50-477f-9eb4-a2bed10becbe