test-3.6:
    image: python:3.6
    script:
        - pip install --upgrade pip
        - pip install numpy
        - pip install numba
        - pip install nose
        - pip install coverage
        - NUMBA_DISABLE_JIT=1 nosetests --with-coverage --cover-erase --cover-package=pyframe

test-3.5:
    image: python:3.5
    script:
        - pip install --upgrade pip
        - pip install numpy
        - pip install numba
        - pip install nose
        - nosetests